#!/usr/bin/env ruby

# A sample pre-deploy hook
#
# Checks the Github status of the build, waiting for a pending build to complete for up to 720 seconds.
#
# Fails unless the combined status is "success"
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_COMMAND
# KAMAL_SUBCOMMAND
# KAMAL_ROLE (if set)
# KAMAL_DESTINATION (if set)

# Only check the build status for production deployments
if ENV["KAMAL_COMMAND"] == "rollback"
  exit 0
end

require "bundler/inline"

# true = install gems so this is fast on repeat invocations
gemfile(true, quiet: true) do
  source "https://rubygems.org"

  gem "sshkit"
  gem "ed25519"
  gem "bcrypt_pbkdf"
end
include SSHKit::DSL

hosts = ENV.fetch('KAMAL_HOSTS').split(',').map do |host|
  "root@#{host}"
end

on(hosts, in: :sequence)do |host|
  puts "uploading test database"
  
  execute("mkdir", "-p", "/var/osm")
  unless test("[ -f /var/osm/colorado.db ]")
    upload! 'colorado.db', '/var/osm/'
  end
end
