#!/bin/sh

set -eux

echo "Booting app version $KAMAL_VERSION on $KAMAL_HOSTS..."
mkdir -p $HOME/osm
if [ -f $HOME/osm/entries.db.zst ]; then
  echo "Using existing database at /var/osm/entries.db.zst"
else
  echo "Downloading database from https://sqlite.knowhere.live/entries.db.zst"
  curl -q --progress-bar -o $HOME/osm/entries.db.zst https://sqlite.knowhere.live/entries.db.zst
fi
