issues:
  exclude-files:
  - query/parse.go
linters:
  enable-all: true
  disable:
  - depguard
  - exhaustruct
  - paralleltest
  - gomoddirectives
  - lll
  - revive
  - tagliatelle

  # cleanup later
  - cyclop
  - dupl
  - funlen
  - gocognit
  - gocyclo
  - gosec
  - maintidx
  - mnd
  - nestif
  - err113
  - varnamelen

  # linters deprecated
  - deadcode
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - nosnakecase
  - maligned
  - scopelint
  - structcheck
  - varcheck