# fly.toml app configuration file generated for knowhere on 2024-02-28T09:29:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knowhere'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "sqlite"
  destination = "/var/osm/"
  initial_size = "15gb"

