version: '3'

interval: "100ms"

tasks:
  format:
    cmds:
    - deno fmt README.md examples/ server/assets/*.ts
    - gofmt -w .
    - shfmt -w bin/*.sh
    - tidy -w 0 -i -m server/assets/index.html
  lint:
    cmds:
    - deno lint examples/
    - golangci-lint run --fix --timeout "10m"
    - shellcheck bin/*.sh
  test: go test -tags fts5 -race -bench . -benchmem ./...
  ci:
    cmds:
    - task: format
    - task: lint
    - task: test
  build:
    cmds:
    - go generate ./...
    - esbuild --tree-shaking=true --bundle --minify server/assets/main.ts --outfile=server/assets/main.js --sourcemap=inline
  default:
    cmds:
    - task: build
    - task: ci
  watch:
    watch: true
    sources:
    - '**/*.go'
    cmds:
    - task: build
    - task: format
    - task: lint
  develop:
    deps: [watch]
    cmds:
    - go run github.com/bokwoon95/wgo run -tags fts5 -race github.com/jtarchie/knowhere server --db .build/entries.db