version: '3'

tasks:
  format:
    cmds:
    - deno fmt README.md
    - gofmt -w .
    - shfmt -w bin/*.sh
  lint:
    cmds:
    - golangci-lint run --fix --timeout "10m"
    - shellcheck bin/*.sh
  test: go run github.com/onsi/ginkgo/v2/ginkgo -tags "fts5" -race -r -p
  ci:
    cmds:
    - task: format
    - task: lint
    - task: test
  default:
    cmds:
    - go generate ./...
    - task: ci
  develop:
    cmds:
    - go generate ./...
    - go run -tags fts5 -race github.com/jtarchie/knowhere server --db .build/entries.db