version: '3'

interval: "100ms"

env:
  CGO_ENABLED: 1
  CGO_CFLAGS: "-O3"

tasks:
  format:
    cmds:
    - deno fmt README.md examples/ server/assets/*.ts commands/runtime
    - deno lint examples/ docs/examples/
    - gofmt -w .
    - shfmt -w bin/*.sh
  lint:
    cmds:
    - deno lint examples/
    - golangci-lint run --fix --timeout "10m"
    - shellcheck bin/*.sh
  test:
    cmds:
    - go test -tags fts5 -race ./...
    - go test -v ./... -bench=. -run="^$" -benchmem
  ci:
    cmds:
    - task: format
    - task: lint
    - task: test
  build:
    cmds:
    - go generate ./...
  default:
    cmds:
    - task: build
    - task: ci
  watch:
    watch: true
    sources:
    - '**/*.go'
    cmds:
    - task: build
    - task: format
    - task: lint
  develop:
    deps: [watch]
    cmds:
    - go run github.com/bokwoon95/wgo run -tags fts5 github.com/jtarchie/knowhere server --db .build/entries.db.zst --runtime-timeout=20s --log-level=debug